### ISSUE TITLE
it's highly detected in a way makes it useless

### ISSUE THREAD

**Issue by ahmedfamhy3** [N3agu/Akame-Loader#4]
if you checked your virus total link you will find it detectable by windows defender and many known AVs

**Comment by N3agu** [comment]
Hello! You can see in the screenshot (posted in the day I uploaded it) that it wasn't detected by WD. Now that AV's got the sample and actually made detection rules for the payload, of course it got detected, that's how it works when you upload it on services that distribute the executable.

You can reFUD the source code with pretty small changes, I updated the README, thank you for the notify! Scrolling down on the repository you will find ways to improve it / make it undetectable again.

Also, this isn't made for illicit use, but for learning and testing purposes, so it's not useless even if it gets detected! Learn how to write code, not how to copy & paste it! Good luck with your studies.
